### ISSUE TITLE
Warning: require Main.php 

### ISSUE THREAD

**Issue by MuneeraAlNufaisi** [SIS-Team/SIS#60]
Warning: require(C:/xampp/htdocs/modules/general/Main.php): failed to open stream: No such file or directory in C:\xampp\htdocs\SIS\index.php on line 4

Fatal error: require(): Failed opening required 'C:/xampp/htdocs/modules/general/Main.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\SIS\index.php on line 4

**Comment by overflowerror** [comment]
Appearently the RELATIVE_ROOT value in your /config.php is not set correctly. Try setting it to "/SIS".

For the future: Please provide a small explanation what you have tried sofar and why you think this might be a bug.
